### PR TITLE
Ref Task #6930: Add rubocop

### PR DESCRIPTION
**Pull request by mabugay1234**
screenshot from 2019-02-20 11-00-29
screenshot from 2019-02-20 13-37-57

### CODE REVIEW

**Comment by mabugay1234** [comment]
ready

**Review by DuongNT1512 — COMMENTED** [review]
ignore lỗi rubocop được báo trong pull này nhé

**Comment by mabugay1234** [comment]
ready

**Comment by mabugay1234** [comment]
screenshot from 2019-02-20 13-37-57

**Pull request merged**
